spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          # search-location: "classpath:/config"
          search-location: "file:///D://dev_zone_aditya//spring//springboot3//config"

server:
  port: 8071
