services:
  accounts:
    image: "adityasrivastva/acc-e4:latest"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bankapp
  loans:
    image: "adityasrivastva/loans:e4"
    container_name: loans-ms
    ports:
      - "8082:8082"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bankapp
  cards:
    image: "adityasrivastva/cards:e4"
    container_name: cards-ms
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bankapp
networks:
  bankapp:
    driver: "bridge"